### ISSUE TITLE
Warning: Unknown props in console

### ISSUE THREAD

**Issue by rlebosse** [danielstocks/react-sortable#39]
I followed the instructions of the example implementation in https://github.com/danielstocks/react-sortable, I have the following warning in the Chrome console :

```
Warning: Unknown props `updateState`, `items`, `draggingIndex`, `sortId`, `outline`, `item`, `isDragging` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```

React-sortable works great but I wondered if there is a way to avoid this warning?

Thanks !

**Comment by Dharmoslap** [comment]
It is fixed in master branch, you can ignore the warning for now. 
Please wait a couple of days for the release.

**Comment by dzhangw7** [comment]
I'm still getting the same thing with the latest version (v1.2.0):

`Warning: Unknown props `field`, `onDelete`, `index`, `draggingIndex`, `onHoverPathChange` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`

**Comment by shiyuegongsui** [comment]
I'm still getting the same thing with the latest version (v2.0.0):
`Warning: Unknown props ``item``, ``items``  on <li> tag. Remove these props from the element. For details`

**Comment by daanishnasir** [comment]
Is there not a way to pass down additional props into the  li element? For instance I need to pass down a unique ID to each li element
